org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

MYAPP_UPLOAD_STORE_FILE=chinnam-release-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=chinnam-key
MYAPP_UPLOAD_STORE_PASSWORD=12345678
MYAPP_UPLOAD_KEY_PASSWORD=12345678